config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

    root to: "handout#houston"

get '/c/houston/may2016.html', to: 'handout#index'

namespace :api do
  namespace :v2 do
    resources :students
  end

end

resources :cohorts do
  resources :projects
end

resources :projects do
  resources :students
end

get '/:city/:cohort/students/new', to: 'students#new', as: 'new_student'
post	'/:city/:cohort/students', to:	'students#create', as: 'create_student'

get 'demo_prints/:id', to: 'handout#demo_prints', as: 'print'

get '/c', to: 'cities#index', as: 'cities'
get '/c/:id', to: 'cities#show', as: 'city'
get '/c/:city/:id', to: 'handout#index', as: 'handout'

end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  belongs_to :city
  has_many :projects, dependent: :destroy
  has_many :students, through: :projects
  has_many :cohortstaffs
  has_many :staffs, through: :cohortstaffs
  validates :demo_day_date, presence: true

  accepts_nested_attributes_for :students


  def display_name
    [city, demo_day_date.strftime("%b %d, %Y")].join("-")
  end

  def to_param
    slug
  end

end

app/controllers/api/v1/cohorts.rb
module API
  module V1
    class Cohorts < Grape::API
      include API::V1::Defaults

      resource :cohorts do
        desc "Return all cohorts"
          params do
            optional :city, type: String, desc: "Cohort city (Houston, Austin, Atlanta, Greenville, Charleston, Orlando, Tampa, Washington DC)"
          end
        get "", root: :cohorts do

          query = Cohort.all.includes(:projects => :students)
          query = query.where(city: permitted_params[:city]) if permitted_params[:city].present?
          query

        end

        desc "Return a specific cohort"
        get ":id", root: :cohort do
          Cohort.find params[:id]
        end


        # desc "Return a student"
        # params do
        #   requires :id, type: String, desc: "ID of the student"
        # end
        # get ":id", root: "student" do
        #   Student.where(id: permitted_params[:id]).first!
        # end



      end
    end
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  # GET /cohorts
  # GET /cohorts.json
  def index
    @cohorts = Cohort.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cohorts }
    end
  end

  # GET /cohorts/1
  # GET /cohorts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cohort }
    end
  end

  # GET /cohorts/new
  def new
    @cohort = Cohort.new
  end

  # GET /cohorts/1/edit
  def edit
  end

  # POST /cohorts
  # POST /cohorts.json
  def create
    @cohort = Cohort.new(cohort_params)

      if @cohort.save
        @cohort.update_attributes(slug: "#{@cohort.city.name.downcase.first(3)}_#{@cohort.demo_day_date.strftime('%b%Y').downcase}")
        redirect_to cities_path, notice: 'Cohort was successfully created.'
      else
        render action: 'new'
      end
  end

  # PATCH/PUT /cohorts/1
  # PATCH/PUT /cohorts/1.json
  def update
    respond_to do |format|
      if @cohort.update(cohort_params)
        format.html { redirect_to @cohort, notice: 'Cohort was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cohorts/1
  # DELETE /cohorts/1.json
  def destroy
    @cohort.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cohort
      @cohort = Cohort.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cohort_params
      params.require(:cohort).permit(:demo_day_date, :slug, :city_id)
    end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_form.html.erb
<%= simple_form_for(@cohort) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :demo_day_date %>
    <%= f.association :city %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn' %>
  </div>
<% end %>

app/views/cohorts/edit.html.erb
<h1>Editing Cohort</h1>

<%= render 'form' %>

<%= link_to 'Show', @cohort %> |
<%= link_to 'Back', cohorts_path %>

app/views/cohorts/new.html.erb
<h1>New Cohort</h1>

<%= render 'form' %>

<%= link_to 'Back', cohorts_path %>

app/views/cohorts/show.html.erb
<% content_for :head do %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<% end %>

<div class="container">
  <p id="notice"><%= notice %></p>

      <ul class="collection with-header">
        <li class="collection-header"><h4>Projects for <%= @cohort.city.name %> - <%= @cohort.demo_day_date.strftime('%m/%d/%Y') %></h4></li>
        <% @cohort.projects.each do |project| %>
        <li class="collection-item"><%= link_to project.app_name, cohort_project_path(@cohort, project) %></li>
        <% end %>
      </ul>
  <%= link_to 'Edit', edit_cohort_path(@cohort) %> |
  <%= link_to 'Back', cohorts_path %>
</div>