config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

    root to: "handout#houston"

get '/c/houston/may2016.html', to: 'handout#index'

namespace :api do
  namespace :v2 do
    resources :students
  end

end

resources :cohorts do
  resources :projects
end

resources :projects do
  resources :students
end

get '/:city/:cohort/students/new', to: 'students#new', as: 'new_student'
post	'/:city/:cohort/students', to:	'students#create', as: 'create_student'

get 'demo_prints/:id', to: 'handout#demo_prints', as: 'print'

get '/c', to: 'cities#index', as: 'cities'
get '/c/:id', to: 'cities#show', as: 'city'
get '/c/:city/:id', to: 'handout#index', as: 'handout'

end

app/controllers/handout_controller.rb
class HandoutController < ApplicationController
  layout :resolve_layout

  def redirect
  end

  def cohorts
    @cohorts = Cohort.all.order(:demo_day_date).order(:city)
  end

  def city
    @city_cohort = Cohort.find_by_slug(params[:id])
    @city_cohorts = Cohort.where(city: @city_cohort.city)
    @city = @city_cohort.city
  end

  def old_urls
    #code
  end

  def index
    @cohort = Cohort.find_by_slug params[:id]
    @courses = @cohort.students.map{|c| c.course}.uniq
    @staffs = Staff.joins(:cohorts).where('cohorts.id =?', @cohort).where('staffs.ta = ?', false)
    @tas = Staff.joins(:cohorts).where('cohorts.id =?', @cohort).where('staffs.ta = ?', true)

    if ["Austin", "Houston"].include? @cohort.city.name
      @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@cohort.city.name.downcase}/header_#{@cohort.city.name.downcase}.jpg"
    elsif ["Dallas", "San Antonio"].include? @cohort.city.name
      @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@cohort.city.name.downcase.gsub(" ", "-")}/header-#{@cohort.city.name.downcase.split.join}.jpg"
    elsif @cohort.city.name == "Las Vegas"
      @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@cohort.city.name.downcase.gsub(" ", "-")}/header_#{@cohort.city.name.downcase.split.last}.jpg"
    elsif @cohort.city.name == "Salt Lake City"
      @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@cohort.city.name.downcase.gsub(/\s*(\S)\S*/, '\1')}/header_#{@cohort.city.name.downcase.gsub(/\s*(\S)\S*/, '\1')}.jpg"
    end

    if ["Austin", "Houston", "Dallas", "San Antonio", "Las Vegas"].include? @cohort.city.name
      @email = @cohort.city.name.downcase.split.join
    elsif @cohort.city.name == "Salt Lake City"
      @email = @cohort.city.name.downcase.gsub(/\s*(\S)\S*/, '\1')
    end
  end


  def demo_prints
    @cohort = Cohort.find_by_slug params[:id]
    @students = @cohort.students
  end

  def houston
    @city = City.find_by_slug("houston")
    @last_houston_cohort = Cohort.joins(:city).where("cities.name = ?", "Houston").last
    redirect_to handout_path(@city.slug, @last_houston_cohort)
  end

  private

  def resolve_layout
    case action_name
    when "demo_prints"
      "print"
    else
      "application"
    end
  end


end

app/helpers/handout_helper.rb
module HandoutHelper
end

app/views/handout/_form.html.erb
<%= simple_form_for @cohort do |f| %>

<% end %>

app/views/handout/_project.html.erb
<div class="project page-break-before">
  <h4><%= response.name.upcase %></h4>
    <div class="table">
        <div>
            <span style="background-image: url(<%= response.profile_pic_link %>)">
        </div>
        <div>
            <h5><%= response.project.app_name.upcase %></h5>
            <h5><%= link_to url_with_protocol(response.project.app_url), url_with_protocol(response.project.app_url), :target => '_blank' %></h5>

        </div>
    </div>

    <p class="hideable"><%= response.bio %></p>
    <p class="hideable"><%= response.project.rationale %></p>


    <h5 class="hideable">TECHNOLOGY USED</h5>

    <p class="hideable"><%= response.project.tech_used.upcase %></p>

      <div>
        <h6>Email Address: <%= mail_to response.email %></h6>
        <h6>GitHub Username: <%= link_to (url_with_protocol(response.github_url) || "").split("/")[3], url_with_protocol(response.github_url), :target => '_blank' %></h6>
        <% unless response.portfolio_url.blank? %>
          <h6>Portfolio: <%= link_to "#{url_with_protocol(response.portfolio_url)}", url_with_protocol(response.portfolio_url), :target => '_blank' %></h6>
        <% end %>
      </div>


</div>

app/views/handout/_staff.html.erb
<% @staffs.sort_by {|lastname| lastname["name"].split(" ").last}.each do |staff| %>
<div class="grid staff hideable page-break-inside">
    <div class="table">
        <div>
            <img src=<%= staff.pic %>>
        </div>
        <div>
            <p>
                <strong><%= staff.name.upcase %></strong>
                <br>
                <i><%= staff.title %></i>
            </p>

            <p><%= staff.bio %></p>
        </div>
    </div>
</div>
<% end %>

app/views/handout/_ta.html.erb
<% @tas.sort_by {|lastname| lastname["name"].split(" ").last}.each do |ta| %>
<div class="grid staff hideable page-break-inside">
    <div class="table">
        <div>
              <img src=<%= ta.pic %>>
        </div>
        <div>
            <p>
                <strong><%= ta.name.upcase %></strong>
                <br>
                <i><%= ta.title %></i>
            </p>

            <p><%= ta.bio %></p>
        </div>
    </div>
</div>
<% end %>

app/views/handout/city.html.erb
<h1><%= @city %> Demo Days</h1>

<% @city_cohorts.order(:demo_day_date).each do |cohort| %>
      <ul>
        <h5 class="c"><li><%= link_to cohort.demo_day_date.strftime('%B %d, %Y'), cohort_path(cohort) %></h5></li>
      </ul>
    <% end %>

app/views/handout/cohorts.html.erb
<div>
  <h1 class="c">All Cohorts</h1>
  <% @cohorts.group_by(&:city).each do |city, cohorts| %>
    <h2><%= link_to city.name, city_path(cohorts.last) %> Demo Day Dates:</h2>
      <% cohorts.each do |cohort| %>
        <ul>
          <h5 class="c"><li><%= link_to cohort.demo_day_date.strftime('%B %d, %Y'), cohort_path(cohort) %> / <%= link_to "Display Print", print_path(cohort) %></h5></li>
        </ul>
      <% end %>
  <% end %>
</div>

app/views/handout/demo_prints.html.erb
<% @students.each do |response| %>
<div class="c project page-break-before">
  <h5>
    <div>
        <span style="background-image: url(<%= response.profile_pic_link %>)">
    </div><br>
    <%= response.name.upcase %>
  </h5>
    <div>
      <h6>Email Address: <%= mail_to response.email %></h6>
      <h6>GitHub Username: <%= link_to (url_with_protocol(response.github_url) || "").split("/")[3], url_with_protocol(response.github_url), :target => '_blank' %></h6>
      <% unless response.portfolio_url.blank? %>
        <h6>Portfolio: <%= link_to "#{url_with_protocol(response.portfolio_url)}", url_with_protocol(response.portfolio_url), :target => '_blank' %></h6>
      <% end %>
    </div>
    <hr>
  <h5><%= response.project.app_name.upcase %></h5>
    <div class="table">
        <div>
            <h5><%= link_to url_with_protocol(response.project.app_url), url_with_protocol(response.project.app_url), :target => '_blank' %></h5>
        </div>
    </div>
    <p class="hideable"><%= response.project.rationale %></p>
    <h5 class="hideable">TECHNOLOGY USED</h5>
    <p class="hideable"><%= response.project.tech_used.upcase %></p>

</div>
<% end %>

app/views/handout/index.html.erb
<div class="grid grid-2-640">
    <div class="vslide c">
        <h1 class="tera">Demo
            <br>Day</h1>
        <h3><%= "The Iron Yard"%></h3>
      <p> <%= @cohort.demo_day_date.strftime('%b %d, %Y') %> </p>



        <%= image_tag "iron-yard-logo.svg", style: "preserveAspectRatio=MinYMin slice" %>
        <br>
        <br>
        <h3><%= @cohort.city.name %></h3>
    </div>

    <div class="vslide">
        <h4>About The Iron Yard</h4>

        <p>The Iron Yard teaches intensive, three-month courses that mentor students into professional junior-level
          programmers. Our program goes far beyond tactical skills and teaches students to think like a software engineer.
          Students have spent the past twelve weeks studying <%= @courses.to_sentence %> and
          today they will present their final projects, which showcase the skills they have learned.</p>

        <%= image_tag "#{@image}", :class => "about-img about-container" %>

    </div>
</div>

<div class="grid">
    <div>
        <h4 class="hideable">Interested in hiring a graduate?</h4>

        <p class="hideable"> <%= "All of our graduates are ready for their first jobs as junior developers. If you meet someone who
        would be a great fit for your team, please feel free to reach out to them directly. Graduates' contact info can be found here.
        If you have questions or want more information about how our job placement program works, get in touch with the houston team
        at "%><%= mail_to "#{@email}@theironyard.com" %>.</p>


    </div>
</div>

<div class="grid hideable page-break-after">
    <div>
        <h4>Interested in taking a class or learning more?</h4>

        <p>Our next classes begin May 22. We are accepting applications now. Applications can be found on our website:
          <a href="http://theironyard.com/apply" target="_blank">theironyard.com/apply</a>. We also offer free classes for kids
          and host a variety of meet-ups and free events. For more information on any of these programs, visit our website or
          email <%= mail_to "#{@email}@theironyard.com" %>.</p>

    </div>
</div>


<div>
  <h3>The <%= @cohort.city.name %> Developers</h3>
</div>

<% @courses.each do |course| %>
  <div class="page-break-before">
      <h4><%= course %></h4>
  </div>
  <div class="grid grid-2-640 projects">
    <% @cohort.students.where(course: course).sort_by {|lastname| lastname["name"].split(" ").last}.each do |response| %>
      <%= render :partial => "project", locals: {response: response} %>
    <% end %>
  </div>
<% end %>



<h4 class="c hideable page-break-before"><%= @cohort.city.name %> Staff Profiles</h4>

    <%= render "staff" %>

<h4 class="c hideable page-break-before"><%= @cohort.city.name %> Teaching Assistants</h4>

    <%= render "ta" %>

<div class="last_page">
<div class="c sponsor page-break-before">
  <h4>Special Thanks For Hosting</h4>
   <div class="sponsor" id="sponsor_size">
     <%= link_to "http://www.tmc.edu/innovation", target: '_blank' do %>
       <%= image_tag "http://www.tmc.edu/innovation/wp-content/uploads/sites/4/2016/04/tmcx-logo.png" %>
     <% end %>
    <br>
  </div>
</div>


<div class="c footer">
   <%= link_to "http://theironyard.com/houston", target: '_blank' do %>
    <%= image_tag "iron-yard-logo.svg", style: "preserveAspectRatio=MinYMin slice" %>
  <% end %>

</div>
</div>

app/views/handout/old_urls.html.erb
<script type="text/javascript">
      window.location = "https://theironyarddemoday.com/c/cohorts";
</script>

app/views/handout/redirect.html.erb
<script type="text/javascript">
      window.location = "https://www.theironyard.com/locations/houston.html";
</script>