config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

    root to: "handout#houston"

get '/c/houston/may2016.html', to: 'handout#index'

namespace :api do
  namespace :v2 do
    resources :students
  end

end

resources :cohorts do
  resources :projects
end

resources :projects do
  resources :students
end

get '/:city/:cohort/students/new', to: 'students#new', as: 'new_student'
post	'/:city/:cohort/students', to:	'students#create', as: 'create_student'

get 'demo_prints/:id', to: 'handout#demo_prints', as: 'print'

get '/c', to: 'cities#index', as: 'cities'
get '/c/:id', to: 'cities#show', as: 'city'
get '/c/:city/:id', to: 'handout#index', as: 'handout'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :students
  belongs_to :cohort, touch: true

  validates :app_name, :app_url, :rationale, :tech_used, :cohort, presence: true


  def display_name
    app_name
  end
end

app/controllers/api/v1/projects.rb
module API
  module V1
    class Projects < Grape::API
      include API::V1::Defaults

      resource :projects do
        desc "Return all projects"
        # params do
        #   optional :group_project, type: Boolean, desc: "See Group Projects"
        # end
        get "", root: :projects do

          query = Project.all

          query
        end


        desc "Return a project"
        params do
          requires :id, type: String, desc: "ID of the project"
        end
        get ":id", root: "project" do
          Project.find params[:id]
        end

        desc "Create a project"
        post do

          Project.create!({
            app_name: params[:project][:app_name],
            cohort_id: params[:project][:cohort],
            rationale: params[:project][:rationale],
            tech_used: params[:project][:tech_used],
            app_url:  params[:project][:app_url],
          })
        end


      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base

    def index
      @cohort = Cohort.find_by_slug params[:cohort_id]
      @projects = @cohort.projects.all
    end

    def show
      @project = Project.find params[:id]
      @cohort = Cohort.find_by_slug params[:cohort_id]
    end


    def new
      @cohort = Cohort.find_by_slug params[:cohort_id]
      @project = @cohort.projects.new
    end


    def edit
      @cohort = Cohort.find_by_slug params[:cohort_id]
      @project = @cohort.projects.find params[:id]
    end

    def create
      @cohort = Cohort.find_by_slug params[:cohort_id]
      @project = @cohort.projects.create(project_params)

      if @project.save
          redirect_to cohort_project_path(@cohort, @project), notice: 'Project created.'
        else
          render :new
      end
    end

    def update
      @cohort = Cohort.find_by_slug params[:cohort_id]
      @project = @cohort.projects.find params[:id]

      if @project.update(project_params)
        redirect_to cohort_project_path(@cohort, @project)
      else
        render 'edit'
      end
    end

    def destroy
      @cohort = Cohort.find_by_slug params[:cohort_id]
      @project = @cohort.projects.find_by_slug params[:id]
      @project.destoy

      redirect_to cities_path
    end

  private

    def project_params
      params.require(:project).permit(:app_name, :app_url, :rationale, :tech_used, :cohort_id)
    end

end

app/views/projects/_form.html.erb
<% content_for :head do %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<% end %>

<div class="container">
  <%= simple_form_for([@cohort, @project]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :app_name%>
      <%= f.input :app_url%>
      <%= f.input :rationale, as: :text, input_html: { maxlength: 762 }, id: "textarea1", class: "materialize-textarea" %>
      <%= f.input :tech_used%>

    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<% content_for :head do %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<% end %>
<div class="container">
  <div class="page-header">
    <h1 align ="center">Edit Project</h1>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/projects/index.html.erb
<% content_for :head do %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<% end %>

<div class="container">

  <ul class="collection with-header">
    <li class="collection-header"><h4><%= @cohort.city.name %> Projects for Demo Day <%= @cohort.demo_day_date.strftime('%m/%d/%Y') %></h4></li>
    <% @cohort.projects.each do |project| %>
      <li class="collection-item"><%= link_to project.app_name, cohort_project_path(@cohort, project) %></li>
    <% end %>
  </ul>
</div>

app/views/projects/new.html.erb
<% content_for :head do %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<% end %>
<div class="container">
  <div class="page-header">
    <h1 align ="center">The Iron Yard Demo Day Project Registration</h1>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/projects/show.html.erb
<% content_for :head do %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<% end %>


<div class="container">

    <div class="row">
      <div class="left-align">
        <h1><%= @project.app_name %></h1>
        <h3><%= @project.app_url %></h3>
      </div>
    </div>
    <div class="row center">
      <h5>Rationale:</h5>
      <p><%= @project.rationale %></p>
    </div>
    <div class="row center">
      <h5>Tech:</h5>
      <p><%= @project.tech_used %></p>
    </div>
    <div class="row">
      <% if @project.students.present? %>
        <ul class="collection with-header">
          <li class="collection-header"><h5>Students on Project</h5></li>
          <% @project.students.each do |student| %>
            <li class="collection-item"><%= link_to student.name, project_student_path(@project, student) %></li>
          <% end %>
        </ul>
        <% end %>
    </div>
    <div class="row">
      <%= link_to "Edit Project", edit_cohort_project_path(@cohort, @project), class: "btn btn-primary" %>
    </div>

<div class="divider"></div>
    <div class="row">
      <h5>Add Student to Project</h5>
    </div>

    <div class="row">
      <div class="col s12 l8">
        <%= simple_form_for([@project, @project.students.build]) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :course, collection: ["Front End Engineering", ".NET Back End Engineering", "Mobile Engineering", "UI"] %>
            <%= f.input :email %>
            <%= f.input :portfolio_url %>
            <%= f.input :github_url %>
            <%= f.input :profile_pic_link %>
            <%= f.input :bio, as: :text, input_html: { maxlength: 762 }, id: "textarea1", class: "materialize-textarea" %>

          </div>

          <div class="form-actions">
            <%= f.button :submit, "Add Student" %>
          </div>
        <% end %>
      </div>
    </div>

</div>