config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

    root to: "handout#houston"

get '/c/houston/may2016.html', to: 'handout#index'

namespace :api do
  namespace :v2 do
    resources :students
  end

end

resources :cohorts do
  resources :projects
end

resources :projects do
  resources :students
end

get '/:city/:cohort/students/new', to: 'students#new', as: 'new_student'
post	'/:city/:cohort/students', to:	'students#create', as: 'create_student'

get 'demo_prints/:id', to: 'handout#demo_prints', as: 'print'

get '/c', to: 'cities#index', as: 'cities'
get '/c/:id', to: 'cities#show', as: 'city'
get '/c/:city/:id', to: 'handout#index', as: 'handout'

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :cohorts

  accepts_nested_attributes_for :cohorts


  def slug
    "#{name.downcase.split.join}"
  end

  def to_param
    slug
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController


def index
  @cities = City.order(:name).all
end


def show
  @city = City.find_by_slug params[:id]

  if ["Austin", "Houston"].include? @city.name
    @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@city.name.downcase}/header_#{@city.name.downcase}.jpg"
  elsif ["Dallas", "San Antonio"].include? @city.name
    @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@city.name.downcase.gsub(" ", "-")}/header-#{@city.name.downcase.split.join}.jpg"
  elsif @city.name == "Las Vegas"
    @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@city.name.downcase.gsub(" ", "-")}/header_#{@city.name.downcase.split.last}.jpg"
  elsif @city.name == "Salt Lake City"
    @image = "https://www.theironyard.com/content/dam/theironyard/locations/#{@city.name.downcase.gsub(/\s*(\S)\S*/, '\1')}/header_#{@city.name.downcase.gsub(/\s*(\S)\S*/, '\1')}.jpg"
  end
end


end

app/views/cities/index.html.erb
<h1>Demo Days</h1>

<% @cities.each do |city| %>
      <ul>
        <h5 class="c"><li><%= link_to city.name, city_path(city) %></h5></li>
      </ul>
<% end %>

app/views/cities/show.html.erb
<div class="c city_page">
  <div class="city_container">
    <div class="city_image">
      <%= image_tag @image %>
      <h1><span class="spacer"><%= @city.name %> Demo Days</span></h1>
    </div>
  </div>

    <div class="cohorts">  <% @city.cohorts.order(:demo_day_date).each do |cohort| %>
      <ul>
        <h5><li><%= link_to cohort.demo_day_date.strftime('%B %d, %Y'), handout_path(@city,cohort) %> <%= link_to " - Add Projects", new_cohort_project_path(cohort), class: "btn btn-primary" if admin_user_signed_in? %>
        <%= link_to " - View Cohort Projects", cohort_projects_path(cohort), class: "btn btn-primary" if admin_user_signed_in? %></h5></li>
      </ul>
      <% end %>
      <br>
      <h5><%= link_to "Add cohort to #{@city.name}", new_cohort_path if admin_user_signed_in? %></h5>
    </div>
  <div class="city_footer">
  <%= image_tag 'iron-yard-logo.svg', class: "bottom" %>
  </div>
</div>